#!/bin/bash

# ---- PATH  ---- #
PATH="$HOME/.local/bin:"$PATH

# ---- Default tools ---- #
export EDITOR="vim"
export PAGER="less"

# ---- XDG BASE DIRECTORY ---- #
# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="$HOME/.local/state"}

# ---- GTK CONFIG  ---- #
export GTK_USE_PORTAL=1

# ---- ALIASES  ---- #
alias ls='ls --color=auto'
alias ls='ls -A --color=auto'
alias rm='trash-put'

