# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:
  blush: "#DA627D"
  plum: "#9A348E"
  salmon: "#FCA17D"
  sky: "#86BBD8"
  tan: "#CC3802"
  teal: "#047E84"
  teal_blue: "#33658A"
  white: "#FFFFFF"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: " {{ .UserName }}"
    foreground: p:white
    background: p:plum
    type: session
    style: diamond
  - properties:
      cache_duration: none
    template: " {{.Icon}} "
    foreground: p:white
    background: p:plum
    type: os
    style: powerline
  - properties:
      cache_duration: none
      style: folder
    template: " {{ .Path }} "
    foreground: p:white
    powerline_symbol: 
    background: p:blush
    type: path
    style: powerline
  - properties:
      branch_icon: ""
      branch_identical_icon: ""
      branch_max_length: 25
      cache_duration: none
      fetch_stash_count: true
      fetch_status: true
      fetch_upstream_icon: true
    template: " {{ .UpstreamIcon }}{{ .HEAD }} {{if .BranchStatus }}{{ .BranchStatus }}{{ end }}{{ if gt (add .Staging.Unmerged .Staging.Deleted .Staging.Added .Staging.Modified .Staging.Untracked) 0 }}<red>\uf444{{ add .Staging.Unmerged .Staging.Deleted .Staging.Added .Staging.Modified .Staging.Untracked }}</>{{ end }}{{ if add .Working.Deleted .Working.Added .Working.Modified }}<#33658A>\uf44d{{  add .Working.Deleted .Working.Added .Working.Modified  }}</>{{ end }}{{ if gt .Working.Untracked 0 }}<grey>\U000f01d8{{ .Working.Untracked }}</>{{ end }}{{ if gt .Working.Unmerged  0 }}<yellow>\U000f140b{{ .Working.Unmerged }}</>{{ end }} "
    foreground: p:white
    powerline_symbol: 
    background: p:salmon
    type: git
    style: powerline
  - properties:
      cache_duration: none
      time_format: "15:04"
    trailing_diamond: 
    template: " ♥ {{ .CurrentDate | date .Format }} "
    foreground: p:white
    background: p:teal_blue
    type: time
    style: diamond
- type: rprompt
  segments:
  - properties:
      always_enabled: false
      cache_duration: none
    leading_diamond: 
    template: "\ue23a {{ .Code }} "
    foreground: "#ffffff"
    background: "#e91e63"
    type: status
    style: diamond
  - properties:
      always_enabled: true
      cache_duration: none
      threshold: 500
    leading_diamond: 
    template: " {{ .FormattedMs }} "
    foreground: "#8f8f8f"
    background: "#3C3C3C"
    type: executiontime
    style: diamond
version: 3
final_space: true
